services:
    whatsbot:
        build: .
        deploy:
            restart_policy:
                max_attempts: 2
        env_file: config.env
        
    okteto:
        build: ./okteto
        deploy:
            restart_policy:
                max_attempts: 365 # I know it's insane
        environment:
            OKTETO_TOKEN: ${OKTETO_TOKEN}
