services:
    whatsbot:
        build: .
        deploy:
            restart_policy:
                max_attempts: 2
        env_file: config.env
        environment:
          SESSION: "$SESSION"
          PMPERMIT_ENABLED: "$PMPERMIT_ENABLED"
          MONGODB_URL: "$MONGODB_URL"
          DEFAULT_TR_LANG: "$DEFAULT_TR_LANG"
          ENABLE_DELETE_ALERT: "$ENABLE_DELETE_ALERT"
          OCR_SPACE_API_KEY: "$OCR_SPACE_API_KEY"

    okteto:
        build: ./okteto
        deploy:
            restart_policy:
                max_attempts: 365 # I know it's insane
        environment:
            OKTETO_TOKEN: ${OKTETO_TOKEN}
